spring:
  application:
    name: matchingengine

  kafka:
    bootstrap-servers: kafka:9092

    consumer:
      group-id: matching-engine
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.value.default.type: com.tradingplatform.matchingengine.event.OrderPlacedEvent
        spring.json.trusted-packages: com.tradingplatform.matchingengine.event
        spring.json.use.type.headers: false
      auto-offset-reset: earliest

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: false

logging:
  level:
    com.tradingplatform.matchingengine: DEBUG



