apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-order-pvc
    namespace: trading-platform
spec: 
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-order
    namespace: trading-platform
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres-order
    template:
        metadata: 
            labels: 
                app: postgres-order
        spec: 
            containers: 
              - name:  postgres
                image: postgres:16-alpine
                ports:
                  - containerPort: 5432
                envFrom:
                  - secretRef:
                      name: postgres-order-secret
                volumeMounts:
                  - name: postgres-storage
                    mountPath: /var/lib/postgresql/data
                readinessProbe:
                  exec:
                    command: ["pg_isready","-U","orderapp","-d","orderdb"]
                  initialDelaySeconds: 5
                  periodSeconds: 5
            volumes:
              - name: postgres-storage
                persistentVolumeClaim:
                  claimName: postgres-order-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-order
  namespace: trading-platform
spec:
  selector:
    app: postgres-order

  ports:
    - port: 5432
      targetPort: 5432

                