apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-service
  namespace: trading-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-service
  template:
    metadata:
      labels:
        app: position-service
    spec:
      containers:
        - name: position-service
          image: position-service:latest
          imagePullPolicy: Never
          env:
            - name: SPRING_DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-position-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-position-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: "384Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"

